// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';
import {docs} from '../models';
import {workflow} from '../models';
import {client} from '../models';

export function CreateTreeNode(arg1:string,arg2:any,arg3:string,arg4:string):Promise<Record<string, any>>;

export function CreateWorkflow(arg1:string,arg2:string):Promise<storage.Workflow>;

export function CreateWorkspace(arg1:string):Promise<storage.Workspace>;

export function DeleteTreeNode(arg1:string):Promise<void>;

export function DeleteWorkspace(arg1:string):Promise<void>;

export function ExecuteByPath(arg1:string,arg2:string,arg3:Record<string, string>):Promise<storage.ExecuteScriptResult>;

export function ExportBek(arg1:string):Promise<string>;

export function GetActiveEnvVars(arg1:string):Promise<Record<string, string>>;

export function GetActiveEnvironmentInfo(arg1:string):Promise<storage.ActiveEnvironmentResult>;

export function GetDocContent(arg1:string):Promise<string>;

export function ImportBek():Promise<storage.Workspace>;

export function ListDocs():Promise<Array<docs.DocEntry>>;

export function ListHistory(arg1:string):Promise<Array<storage.HistoryEntry>>;

export function ListJobRuns(arg1:string):Promise<Array<storage.JobRun>>;

export function Load():Promise<storage.LoadResult>;

export function ManageEnvs(arg1:storage.ManageEnvsInput):Promise<any>;

export function ResolveRequestByPath(arg1:string,arg2:string):Promise<storage.ResolvedRequestContext>;

export function RunWorkflow(arg1:string,arg2:string):Promise<workflow.RunResult>;

export function Save(arg1:storage.SavePayload):Promise<void>;

export function SaveRequest(arg1:storage.RequestData):Promise<void>;

export function SaveWorkflowGraph(arg1:string,arg2:string):Promise<void>;

export function ScheduleJob(arg1:string,arg2:number):Promise<void>;

export function SendRequest(arg1:client.HTTPRequest,arg2:string,arg3:string,arg4:string):Promise<client.HTTPResponse>;

export function UpdateLatestHistoryTests(arg1:string,arg2:string):Promise<void>;

export function UpdateTreeNode(arg1:string,arg2:string):Promise<void>;

export function UpdateWorkspace(arg1:string,arg2:string):Promise<void>;
