// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTreeNode(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateTreeNode'](arg1, arg2, arg3, arg4);
}

export function CreateWorkflow(arg1, arg2) {
  return window['go']['main']['App']['CreateWorkflow'](arg1, arg2);
}

export function CreateWorkspace(arg1) {
  return window['go']['main']['App']['CreateWorkspace'](arg1);
}

export function DeleteTreeNode(arg1) {
  return window['go']['main']['App']['DeleteTreeNode'](arg1);
}

export function DeleteWorkspace(arg1) {
  return window['go']['main']['App']['DeleteWorkspace'](arg1);
}

export function ExecuteByPath(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteByPath'](arg1, arg2, arg3);
}

export function ExportBek(arg1) {
  return window['go']['main']['App']['ExportBek'](arg1);
}

export function GetActiveEnvVars(arg1) {
  return window['go']['main']['App']['GetActiveEnvVars'](arg1);
}

export function GetActiveEnvironmentInfo(arg1) {
  return window['go']['main']['App']['GetActiveEnvironmentInfo'](arg1);
}

export function GetDocContent(arg1) {
  return window['go']['main']['App']['GetDocContent'](arg1);
}

export function ImportBek() {
  return window['go']['main']['App']['ImportBek']();
}

export function ListDocs() {
  return window['go']['main']['App']['ListDocs']();
}

export function ListHistory(arg1) {
  return window['go']['main']['App']['ListHistory'](arg1);
}

export function ListJobRuns(arg1) {
  return window['go']['main']['App']['ListJobRuns'](arg1);
}

export function Load() {
  return window['go']['main']['App']['Load']();
}

export function ManageEnvs(arg1) {
  return window['go']['main']['App']['ManageEnvs'](arg1);
}

export function ResolveRequestByPath(arg1, arg2) {
  return window['go']['main']['App']['ResolveRequestByPath'](arg1, arg2);
}

export function RunWorkflow(arg1, arg2) {
  return window['go']['main']['App']['RunWorkflow'](arg1, arg2);
}

export function Save(arg1) {
  return window['go']['main']['App']['Save'](arg1);
}

export function SaveRequest(arg1) {
  return window['go']['main']['App']['SaveRequest'](arg1);
}

export function SaveWorkflowGraph(arg1, arg2) {
  return window['go']['main']['App']['SaveWorkflowGraph'](arg1, arg2);
}

export function ScheduleJob(arg1, arg2) {
  return window['go']['main']['App']['ScheduleJob'](arg1, arg2);
}

export function SendRequest(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendRequest'](arg1, arg2, arg3, arg4);
}

export function UpdateLatestHistoryTests(arg1, arg2) {
  return window['go']['main']['App']['UpdateLatestHistoryTests'](arg1, arg2);
}

export function UpdateTreeNode(arg1, arg2) {
  return window['go']['main']['App']['UpdateTreeNode'](arg1, arg2);
}

export function UpdateWorkspace(arg1, arg2) {
  return window['go']['main']['App']['UpdateWorkspace'](arg1, arg2);
}
